sudo: required
before_install:
    - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
    - sudo apt-get -qq update
    - sudo apt-get install -y g++-4.9
    - export CXX="g++-4.9" CC="gcc-4.9"
language: cpp
script:
    - cmake .
    - make
