sudo: required
before_install:
    - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
    - sudo apt-get -qq update
    - sudo apt-get install -y g++-4.9
    - export CXX="g++-4.9" CC="gcc-4.9"
    - sudo add-apt-repository "deb http://archive.ubuntu.com/ubuntu/ xenial main"
    - sudo apt-get -qq update
    - sudo apt-get install -y --no-install-recommends libboost1.58-dev
language: cpp
script:
    - cmake .
    - make
